name: Build the docs

on:
  pull_request:
    branches:
      - main
      - docs

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv pip install ".[optimization,cheminfo,docs]" --system

      - name: Build docs
        run: |
          ls -l docs/*
          mkdocs build
